In [7]:
import pandas as pd 

df = pd.read_csv('en openfoodfacts org products.csv')

In [8]:
df.head(5)

,code,product_name,quantity,packaging_en,brands_en,categories_en,origins_en,labels_en,countries_en,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups_en,environmental_score_score,environmental_score_grade,main_category_en,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g
0,301762042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
1,2045652893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
2,3017620422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
3,490000030464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
4,11702334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['pnns_groups_2'].value_counts()

pnns_groups_2
unknown                             8484
Sweets                               510
Biscuits and cakes                   382
Milk and yogurt                      363
One-dish meals                       283
Dairy desserts                       279
Bread                                251
Cheese                               194
Dressings and sauces                 189
Breakfast cereals                    185
Chocolate products                   176
Meat                                 169
Cereals                              162
Sweetened beverages                  148
Ice cream                            131
Processed meat                       128
Plant-based milk substitutes         113
Vegetables                            92
Artificially sweetened beverages      83
Alcoholic beverages                   80
Unsweetened beverages                 69
Fats                                  68
Fish and seafood                      65
Appetizers                            64
Salty and fatty products              61
Pizza pies and quiches                59
Fruits                                53
Legumes                               46
Fruit juices                          42
Nuts                                  36
Eggs                                  31
Potatoes                              28
Waters and flavored waters            25
Sandwiches                            24
Soups                                 24
Dried fruits                          20
Teas and herbal teas and coffees      12
Pastries                               4
Fruit nectars                          1
Name: count, dtype: int64

In [10]:
df_category = df['main_category_en'].value_counts()

df_category.to_csv('test.csv')

In [11]:
df['pnns_groups_1'].value_counts()

pnns_groups_1
unknown                    8484
Sugary snacks              1072
Milk and dairy products     967
Cereals and potatoes        672
Beverages                   493
Fish Meat Eggs              393
Composite foods             366
Fat and sauces              257
Fruits and vegetables       189
Salty snacks                161
Alcoholic beverages          80
Name: count, dtype: int64

In [12]:
dividing = df['pnns_groups_2'].value_counts()

dividing.to_csv('future_dividing.csv')

PermissionError: [Errno 13] Permission denied: 'future_dividing.csv'

In [ ]:
df['pnns_groups_1'].value_counts()

pnns_groups_1
Sugary snacks              1072
Milk and dairy products     967
Cereals and potatoes        672
Beverages                   493
Fish Meat Eggs              393
Composite foods             366
Fat and sauces              257
Fruits and vegetables       189
Salty snacks                161
Alcoholic beverages          80
Name: count, dtype: int64

In [45]:
sample = df[df['pnns_groups_2'] == 'Milk and yogurt']

sample.to_csv('sample.csv')

In [63]:
df[df['pnns_groups_2'] == 'Fruit nectars'].sample(1)

,code,product_name,quantity,packaging_en,brands_en,categories_en,origins_en,labels_en,countries_en,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups_en,environmental_score_score,environmental_score_grade,main_category_en,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g
8574,6470910139680,Nectar multifruits - €.C.O.+ - 2L,2000.0g,NaN,C-o,"Plant-based foods and beverages,Beverages,Plan...",NaN,NaN,Finland,unknown,Beverages,Fruit nectars,"Beverages,Fruit nectars",NaN,NaN,Multifruit nectars,NaN,NaN

In [ ]:
IF pnns_groups_2 == 'Milk and yogurt':
    IF categories_en IN 'Yogurt':
        carbon-footprint_100g = 1.5
    ELIF categories_en IN 'Tea' AND packaging_en IN 'Paperboard':
        carbon-footprint_100g = 2
    ELIF categories_en IN 'Tea' AND packaging_en IN 'Plastic':
        carbon-footprint_100g = 10
    ELSE:
        carbon-footprint_100g = 2

IF pnns_groups_2 == 'Milk and yogurt':
        carbon-footprint_100g = 2

In [ ]:
df_sweet = df[df['pnns_groups_2'] == 'Sweets']

df_sweet.shape

(510, 18)

In [ ]:


df.loc[df['pnns_groups_2'] == 'Sweets', 'carbon-footprint_100g'] = 2.95


df.loc[df['pnns_groups_2'] == 'Sweets', 'carbon-footprint_100g'] = 2

,code,product_name,quantity,packaging_en,brands_en,categories_en,origins_en,labels_en,countries_en,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups_en,environmental_score_score,environmental_score_grade,main_category_en,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g
12088,6410220009006,Oat snack mango,NaN,"Metal,Plastic,Recyclable Metals,Aluminium,Cont...",Fazer-norway-as,"Plant-based foods and beverages,Fermented food...",Finland,No gluten,Finland,b,Sugary snacks,Sweets,"Sugary snacks,Sweets",NaN,NaN,Oat milk yogurts,2.0,NaN
8232,6410405197658,Hunaja,500 g,NaN,Pirkka,"Breakfasts,Spreads,Sweet spreads,Bee products,...",NaN,NaN,Finland,unknown,Sugary snacks,Sweets,"Sugary snacks,Sweets",NaN,NaN,Honeys,2.0,NaN
7469,6411401037153,Pax original recipe,NaN,NaN,Fazer,"Snacks,Sweet snacks,Cocoa and its products,Con...",NaN,NaN,"Finland,France",d,Sugary snacks,Sweets,"Sugary snacks,Sweets",NaN,unknown,Bonbons,2.0,NaN
10253,704039020496,Scottish Fudge,250g,NaN,The-broons,"Snacks,Sweet snacks,Confectioneries,Caramels",NaN,Green Dot,Finland,unknown,Sugary snacks,Sweets,"Sugary snacks,Sweets",NaN,NaN,Caramels,2.0,NaN
11547,5411188128601,Skyr Vanille,0.4 kg,"Metal,Pot,Recyclable Metals,Aluminium,Plastique",Danone-as,"Plant-based foods and beverages,Dairies,Fermen...",NaN,No gluten,"Finland,France,Germany,Switzerland",a,Sugary snacks,Sweets,"Sugary snacks,Sweets",80.0,a,Soy milk yogurts,2.0,NaN

In [68]:
df_test = pd.read_csv('intermediate.csv', sep=';')

df_test.sample(5)

,source_product_category,category_name,kg_CO2_min,kg_CO2_max,average
52,Chips and snacks,Appetizers,1.7,2.5,2.10
21,Tomatoes and cucumbers,NaN,0.1,3.0,1.55
44,"Salmon and trout, foreign, farmed",NaN,4.1,6.7,5.40
49,"Bread, biscuits, and pastries",Biscuits and cakes,0.5,4.5,2.50
10,Milk,Milk and yogurt,0.9,1.2,1.05